<?php
if (!defined('DP_BASE_DIR')) {
	die('You should not access this file directly.');
}
//Do not edit this file by hand, it will be overwritten by the configuration utility. 
$PROJDESIGN_CONFIG['show_task_descriptions'] = '1';
$PROJDESIGN_CONFIG['chars_task_descriptions'] = '400';
?>
